<?php

/*
Plugin Name: Memcached
Description: Memcached backend for the WP Object Cache.
Version: 2.0.2
Plugin URI: http://wordpress.org/extend/plugins/memcached/
Author: Ryan Boren, Denis de Bernardy, Matt Martz

Install this file to wp-content/object-cache.php
*/

// Users with setups where multiple installs share a common wp-config.php or $table_prefix
// can use this to guarantee uniqueness for the keys generated by this object cache



if (!class_exists('Memcache')) {
	return;
}



if ( !defined( 'OMEMCACHED_SERVERS' ) )
	       define( 'OMEMCACHED_SERVERS', '127.0.0.1:22122' );

if ( !defined( 'WP_CACHE_KEY_SALT' ) )
	define( 'WP_CACHE_KEY_SALT', md5(DB_NAME) );

if (strpos(OMEMCACHED_SERVERS,'cache.amazonaws.com') && class_exists('Memcached')) {
	require(__DIR__.'/object-cache-aws.php');
} else {
	$GLOBALS['memcached_servers'] = explode(',',OMEMCACHED_SERVERS);
	require(__DIR__.'/object-cache-normal.php');

}

?>
